# Generated by Django 3.2.7 on 2021-09-29 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_productgallery'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productgallery',
            options={'verbose_name': 'Product Gallery', 'verbose_name_plural': 'Product Galleries'},
        ),
    ]
