# Generated by Django 3.2.7 on 2021-09-22 00:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_account_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='phone_num',
        ),
    ]
