# Generated by Django 3.2.7 on 2021-09-26 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='terms',
            field=models.BooleanField(default=True),
        ),
    ]
